on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
    - name: Jenkinsfile Runner Prepackaged
      uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}